### ISSUE TITLE
problem with pairing

### ISSUE THREAD

**Issue by renandw** [peros550/esp-homekit-multiple-sensors#8] opened 2021-01-23 00:10 UTC
Hello Peros.
Sorry to bother you once more.
I compiled your code and was using it without a problem.
A couple of months ago you updated it. And today I tried to make it work.
But I can't pair it

here is the logs

```
Function called without core lock
CONNECTED TO >>> WIFI <<<
HOSTNAME set>>>>>:HomekitSensor-D44962
manuf='manuf_unknown' serial='F4:CF:A2:D4:49:62' model='model_unknown' revision='0.0.0' c#=0
Free Heap: 25356
>>> HomeKit: Starting server
>>> HomeKit: Formatting HomeKit storage at 0x8c000
>>> wifi_config: Stopping HTTP server
>>> HomeKit: Generated new accessory ID: 2C:DD:43:4E:83:1B
>>> HomeKit: Generated new accessory key
>>> HomeKit: Configuring mDNS
HomeKit: adding mDNS TXT record md=model_unknown
HomeKit: adding mDNS TXT record pv=1.0
HomeKit: adding mDNS TXT record id=2C:DD:43:4E:83:1B
HomeKit: adding mDNS TXT record c#=1
HomeKit: adding mDNS TXT record s#=1
HomeKit: adding mDNS TXT record ff=0
HomeKit: adding mDNS TXT record sf=1
HomeKit: adding mDNS TXT record ci=9
SERVER JUST INITIALIZED
>>> wifi_config: Stopping DNS server
mDNS: Delaying probe until IP is acquired
Got IP, resuming mDNS
mDNS: Probing 1 HomekitSensor-D44962
mDNS: Failed to send broadcast (code 118)
mDNS: Probing 1 HomekitSensor-D44962
mDNS: Failed to send broadcast (code 118)
ip:192.168.100.25,mask:255.255.255.0,gw:192.168.100.1
mDNS: Probing 2 HomekitSensor-D44962
mDNS: Probing 3 HomekitSensor-D44962
mDNS: Probe successful, announcing HomekitSensor-D44962 TXT md=model_unknown pv=1.0 id=2C:DD:43:4E:83:1B c#=1 s#=1 ff=0 sf=1 ci=9
mDNS: Announcing 1 HomekitSensor-D44962
mDNS: Announcing 2 HomekitSensor-D44962
mDNS: Announcing 3 HomekitSensor-D44962
mDNS: Announcing 4 HomekitSensor-D44962
```

Some help would be awesome!!

**Comment by peros550** [comment] 2021-01-23 06:34
Hi @renandw ,

I hope you are doing great and stay safe as much as possible in these difficult times. 

When saying you can't pair it, what do you mean? You can't see the new accessory in home app after setting wifi?

 The following part of your log: 

`mDNS: Failed to send broadcast (code 118)`

is something I also faced when tried to install this firmware on my sister's home where the accessory would not become available in home app. I had a discussion with maxim about this [here](https://github.com/maximkulkin/esp-homekit/issues/175) who mentioned that possibly a wifi issue may be the root cause of the issue. 

So long story short, I messed up with wifi settings on that router (a Tp-Link ) and changed the channel selection from auto to some random one. After a few tries the issue resolved and I was able to see the accessory. If you have access to a Mac, I can propose a Mac app ([Wifi Explorer Lite](https://apps.apple.com/gr/app/wifi-explorer-lite/id1408727408?mt=12)) which is nice tool for site surveying your location for existing Wifi networks. WIth that tool you can see how crowded each channel is and you can make an educated guess on which channel to pick.    

If the above step is not good, maybe you could downgrade the code to a previous version so that we can see if the issue really comes from the new updates and try to isolate further the issue.

**Comment by renandw** [comment] 2021-01-23 11:36
Hi @peros550. Thanks for the quick reply.
There are difficult times indeed.
I am glad that my family is doing well. But not everybody have the same lucky ://
I hope that you are well too!!

I've tried the updated version and it kind of freeze after this `mDNS: Announcing 4 HomekitSensor-D44962`. I can see it in the home.app and type the homekit password. But it seems freezes.
![image](https://user-images.githubusercontent.com/50704421/105577061-98a8db00-5d4d-11eb-9671-9abd6af77fee.jpeg)

And then I've tried to run a older version that I compiled in my raspberry. And it worked.
I reconfigured my route just for sake. But other accessories and even the older version worked :/

**Comment by peros550** [comment] 2021-01-23 12:24
The latest version includes a webserver for some additional settings & configuration. The commit of 4th Oct 2020 is the one that works best for you right?

**Comment by renandw** [comment] 2021-01-23 12:48
I guess that the one in my raspberry that works is the commit from Jun or Aug 2020.

**Comment by peros550** [comment] 2021-01-24 06:45
@renandw I cannot reproduce the issue and it's more difficult to isolate it. For start, I just noticed esp-homekit library has an update (8-Jan-2021) which I haven't incorporated yet in my code. Can you please update locally and let me know if it works for you?

in order to update:
```
cd components/common/homekit/
git pull origin master
```

then go back to this repo's root folder and rebuild: 

```
cd ../../..
make -C examples/multiple_sensors_ac/ rebuild
```

Something more, if you are compiling locally, but trying to install through OTA, then you might need to go the that line: 

`c_hash=1; revision.value.string_value="0.0.1"; //cheat line`

and comment it.

**Comment by renandw** [comment] 2021-01-24 13:46
Hi peros.
I appreciate your time.

I’ve tried what you oriented me. But unfortunately it did not worked.
Than I saw that you used Maxim “led status library”. But the led wasn’t blinking. I looked the code and saw that “pin 2” two was defined  2 times. One in led_gpio and one in LED_STATUS_PIN. I thought that it maybe was the source of the problem. But it wasn’t.
I will keep looking.
Thanks peros

**Comment by peros550** [comment] 2021-01-24 16:45
Today I was at my sister's house again and brought my Wemos minis together. I tried to preproduce the issue and was able to see the issue as you described in the first message even after updating to latest esp-homekit. What really helped was to change Wifi channel at the router. I found that using [HAA](https://github.com/RavenSystem/esp-homekit-devices) was much more stable than my firmware. 

Same firmware, at my home's wifi pairs always. 

You mentioned that if you use firmware dated June 2020, it pairs successfully ?

**Comment by renandw** [comment] 2021-01-24 19:05
> You mentioned that if you use firmware dated June 2020, it pairs successfully ?

Exactly. I got new AC and just changed the raw data to work with the new one.
Of course it doesn't have the features that you updated. But is really great. I've tried to work with maxim example of an AC. But is not for me. Not now, at least.

> and was able to see the issue as you described

I am glad and also sad about it :/

**Comment by peros550** [comment] 2021-01-24 21:24
I will troubleshoot further on my end. It will take some time though. Maybe something I added lately is not playing well. 

Just by any chance, did you try changing the wi-fi channel on your router?

**Comment by renandw** [comment] 2021-01-24 23:19
Yes, peros. I’ve tried every single channel from the 13 available.
Great man.
I can’t thank you enough for the attention and time. Thanks a lot

**Comment by cab113** [comment] 2021-01-28 01:08
@peros550 and @renandw  i managed to pair this by looking at the other example and this is where the homekit server port may be having a conflict 
by deleting this lines 

@line 1285 
char *custom_hostname = name.value.string_value;
		struct netif *netif = sdk_system_get_netif(STATION_IF);
			if (netif) {
				printf("HOSTNAME set>>>>>:%s\n", custom_hostname);
				LOCK_TCPIP_CORE();
				dhcp_release_and_stop(netif);
				netif->hostname = "foobar";
				netif->hostname =custom_hostname;
				dhcp_start(netif);
				UNLOCK_TCPIP_CORE();
			}
after deleting this line add 
below @ line 1307 

sdk_os_timer_setfn(&extra_func_timer, sensor_worker, NULL);

			sdk_os_timer_disarm(&extra_func_timer);

it paired after 3 or 4 tries as memory is low so it was "Failed to compute SRP shared secret (code -2)" i did three reboot and after 1 minute it paired with all accessories. 

have been enjoying your old code on A/C for a while so thank you and hope this helps

**Comment by peros550** [comment] 2021-01-28 07:20
@renandw @cab113 sorry, I was a bit busy these days and didn't reply back. I will further troubleshoot on my end at the following days and most probably at the weekend. 

Lines 1285-1295 are about setting a custom host-name so the device can appear at router's menu with a familiar name. I guess this function may be used only if device is already paired so that we can save some RAM during a non paired state. If you don't need setting the hostname, you can remove it all together. 

The code includes a cheat line [#1302  ](https://github.com/peros550/esp-homekit-multiple-sensors/blob/b7304a50e90e53c697e7d0fa210be079f403f6c5/examples/multiple_sensors_ac/main.c#L1302) 

This one must be allowed if you are flashing your device by wire but if you are using OTA method, then it must be removed before compiling.  

Could you please try to download the code (commit: db8ff7f8f066c8afb7e067c33501d7016df8eae7) as posted in 4th Oct 2020 and let me know if the issue is still there? This would be a big help in my troubleshooting.

**Comment by cab113** [comment] 2021-01-29 04:24
@peros550 Yes the issue is present in this commit as well my log is attached after flashing, waiting for pairing it stops responding 
ESP-Open-SDK ver: 0.0.1 compiled @ Jan 29 2021 17:09:06
phy ver: 273, pp ver: 8.3

SDK version:0.9.9
>>> wifi_config: Initializing WiFi config
!!! wifi_config: No configuration found
>>> wifi_config: Starting AP mode
>>> wifi_config: Starting DHCP server
mode : sta(f4:cf:a2:c8:89:98) + softAP(f6:cf:a2:c8:89:98)
add if0
add if1
bcn 100
>>> wifi_config: Starting WiFi scan
>>> wifi_config: Starting DNS server
>>> wifi_config: Starting HTTP server
scandone
scandone
scandone
add 1
aid 1
station: c2:63:41:71:f0:eb join, AID = 1
scandone
scandone
>>> wifi_config: Connecting to LIGHT HOUSE
scandone
!!! wifi_config: WiFi scan failed
scandone
add 0
aid 19
cnt

connected with test wifi, channel 2
dhcp client start...
ip:192.168.1.39,mask:255.255.255.0,gw:192.168.1.1
station: c2:63:41:71:f0:eb leave, AID = 1
rm match
>>> wifi_config: Connected to WiFi network
bcn 0
del if1
mode : sta(f4:cf:a2:c8:89:98)
Function called without core lock
CONNECTED TO >>> WIFI <<<
HOSTNAME set>>>>>:HomekitSensor-C88998
manuf='manuf_unknown' serial='F4:CF:A2:C8:89:98' model='model_unknown' revision='0.0.0' c#=0
Free Heap: 21604
>>> HomeKit: Starting server
>>> HomeKit: Formatting HomeKit storage at 0x8c000
>>> HomeKit: Generated new accessory ID: 3F:BD:AE:C9:DB:CA
>>> wifi_config: Stopping HTTP server
>>> HomeKit: Generated new accessory key
>>> HomeKit: Configuring mDNS
HomeKit: adding mDNS TXel_unknown
HomeKit: adding mDNSit: adding mDNS TXT record s#=1
HomeKit: adding mDNS TXT record ff=0
HomeKit: adding mDNS TXT record sf=1
HomeKit: adding mDNS TXT record ci=9
SERVER JUST INITIALIZED
>>> wifi_config: Stopping DNS server
mDNS: Delaying probe until IP is acquired
Got IP, resuming mDNS
mDNS: Probing 1 HomekitSensor-C88998
mDNS: Failed to send broadcast (code 118)
mDNS: Probing 1 HomekitSensor-C88998
mDNS: Failed to send broadcast (code 118)
mDNS: Probing 2 HomekitSensor-C88998
mDNS: Failed to send broadcast (code 118)
ip:192.168.1.39,mask:255.255.255.0,gw:192.168.1.1
mDNS: Probing 3 HomekitSensor-C88998
mDNS: Probe successful, announcing HomekitSensor-C88998 TXT md=model_unknown pv=1.0 id=3F:BD:AE:C9:DB:CA c#=1 s#=1 ff=0 sf=1 ci=9
mDNS: Announcing 1 HomekitSensor-C88998
mDNS: Announcing 2 HomekitSensor-C88998
mDNS: Announcing 3 HomekitSensor-C88998
mDNS: Announcing 4 HomekitSensor-C88998

**Comment by cab113** [comment] 2021-01-29 04:34
Again by removing this  
   
char *custom_hostname = name.value.string_value;
	struct netif *netif = sdk_system_get_netif(STATION_IF);
    if (netif) {
		 printf("HOSTNAME set>>>>>:%s\n", custom_hostname);
        LOCK_TCPIP_CORE();
        dhcp_release_and_stop(netif);
        netif->hostname = "foobar";
		netif->hostname =custom_hostname;
        dhcp_start(netif);
        UNLOCK_TCPIP_CORE();
    }

It paired with all accessories 


pm_task_hdl : 3fff0338, prio:1, stack:176
frc2_timer_task_hdl:0x3fff4e08, prio:12, stack:200

ESP-Open-SDK ver: 0.0.1 compiled @ Jan 29 2021 17:20:31
phy ver: 273, pp ver: 8.3

SDK version:0.9.9
>>> wifi_config: Initializing WiFi config
>>> wifi_config: Connecting to mode : sta(f4:cf:a2:c8:89:98)
add if0
scandone
add 0
aid 19
cnt

connected with test wifi , channel 2
dhcp client start...
ip:192.168.1.39,mask:255.255.255.0,gw:192.168.1.1
>>> wifi_config: Connected to WiFi network
CONNECTED TO >>> WIFI <<<
manuf='manuf_unknown' serial='' model='model_unknown' revision='0.0.0' c#=0
Free Heap: 36584
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: xxxxxxxxxxxx
>>> HomeKit: Configuring mDNS
HomeKit: adding mDNS TXT record md=model_unknown
HomeKit: adding mDNS TXT record pv=1.0
HomeKit: adding mDNS TXT record id=xxxxxxxxxxxx
HomeKit: adding mDNS TXT record c#=1
HomeKit: adding mDNS TXT record s#=1
HomeKit: adding mDNS TXT record ff=0
HomeKit: adding mDNS TXT record sf=1
HomeKit: adding mDNS TXT record ci=9
SERVER JUST INITIALIZED
mDNS: Delaying probe until IP is acquired
Got IP, resuming mDNS
mDNS: Probing 1 HomekitSensor-C88998
mDNS: Probing 1 HomekitSensor-C88998
mDNS: Probing 2 HomekitSensor-C88998
mDNS: Probing 3 HomekitSensor-C88998
mDNS: Probe successful, announcing HomekitSensor-C88998 TXT md=model_unknown pv=1.0 id=xxxxxxxxxxxx c#=1 s#=1 ff=0 sf=1 ci=9
mDNS: Announcing 1 HomekitSensor-C88998
>>> HomeKit: [Client 1] Got new client connection from 192.168.1.42
CLIENT JUST CONNECTED
>>> HomeKit: [Client 1] Pair Setup Step 1/3
mDNS: Announcing 2 HomekitSensor-C88998
mDNS: Announcing 3 HomekitSensor-C88998
mDNS: Announcing 4 HomekitSensor-C88998
>>> HomeKit: [Client 1] Pair Setup Step 2/3
>>> HomeKit: [Client 1] Pair Setup Step 3/3
>>> HomeKit: Added pairing with 0x0
CLIENT JUST PAIRED
>>> HomeKit: Configuring mDNS
HomeKit: adding mDNS TXT record md=model_unknown
HomeKit: adding mDNS TXT record pv=1.0
HomeKit: adding mDNS TXT record id=xxxxxxxxxxxx
HomeKit: adding mDNS TXT record c#=1
HomeKit: adding mDNS TXT record s#=1
HomeKit: adding mDNS TXT record ff=0
HomeKit: adding mDNS TXT record sf=0
HomeKit: adding mDNS TXT record ci=9
>>> HomeKit: [Client 1] Successfully paired
>>> HomeKit: [Client 1] Closing client connection from 192.168.1.42
CLIENT JUST DISCONNECTED
>>> HomeKit: [Client 1] Got new client connection from 192.168.1.42
CLIENT JUST CONNECTED
>>> HomeKit: [Client 1] Pair Verify Step 1/2
>>> HomeKit: [Client 1] Pair Verify Step 2/2
>>> HomeKit: [Client 1] Found pairing with 0x0
mDNS: Probing 1 HomekitSensor-C88998
CLIENT JUST VERIFIED







HTTP FLAG IS 0







Free Heap: 26756
http task started
Started UDP logging2
Found pairing, starting timers
HTTP get task starting...
Free Heap: 20516
Running HTTP get request...
Temporarily killing http task, sensor values are not ready
Initializing AC parameters
>>> HomeKit: [Client 1] Verification successful, secure session established
>>> HomeKit: [Client 1] Get Accessories
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.10 ("Active")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.11 ("Current Temperature")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.12 ("Current Heater Cooler State")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.13 ("Target Heater Cooler State")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.14 ("Cooling Threshold Temperature")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.15 ("Heating Threshold Temperature")
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.10 ("On")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.13 ("Current Temperature")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.16 ("Current Ambient Light Level")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.19 ("Motion Detected")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.22 ("Current Relative Humidity")
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.10 ("Active")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.11 ("Current Temperature")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.12 ("Current Heater Cooler State")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.13 ("Target Heater Cooler State")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.14 ("Cooling Threshold Temperature")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 1.15 ("Heating Threshold Temperature")
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.10 ("On")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.13 ("Current Temperature")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.16 ("Current Ambient Light Level")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.19 ("Motion Detected")
>>> HomeKit: [Client 1] Subscribed to notifications of characteristic 2.22 ("Current Relative Humidity")
>>> HomeKit: [Client 1] Get Characteristics
>>> HomeKit: [Client 1] Requested characteristic info for 2.19 ("Motion Detected")
>>> HomeKit: [Client 1] Requested characteristic info for 2.10 ("On")
>>> HomeKit: [Client 1] Requested characteristic info for 2.22 ("Current Relative Humidity")
>>> HomeKit: [Client 1] Requested characteristic info for 2.13 ("Current Temperature")
>>> HomeKit: [Client 1] Requested characteristic info for 2.16 ("Current Ambient Light Level")
>>> HomeKit: [Client 1] Requested characteristic info for 1.13 ("Target Heater Cooler State")
>>> HomeKit: [Client 1] Requested characteristic info for 1.11 ("Current Temperature")
>>> HomeKit: [Client 1] Requested characteristic info for 1.12 ("Current Heater Cooler State")
>>> HomeKit: [Client 1] Requested characteristic info for 1.14 ("Cooling Threshold Temperature")
>>> HomeKit: [Client 1] Requested characteristic info for 1.15 ("Heating Threshold Temperature")
>>> HomeKit: [Client 1] Requested characteristic info for 1.10 ("Active")
mDNS: Probing 2 HomekitSensor-C88998
mDNS: Probing 3 HomekitSensor-C88998
mDNS: Probe successful, announcing HomekitSensor-C88998 TXT md=model_unknown pv=1.0 id=xxxxxxxxxxxx c#=1 s#=1 ff=0 sf=0 ci=9
>>> HomeKit: [Client 2] Got new client connection from 192.168.1.52
>>> HomeKit: [Client 1]  Have existing connection from 192.168.1.42
CLIENT JUST CONNECTED
>>> HomeKit: [Client 2] Pair Verify Step 1/2
mDNS: Announcing 1 HomekitSensor-C88998
>>> HomeKit: [Client 3] Got new client connection from 192.168.1.19
>>> HomeKit: [Client 2]  Haing connection from 192.168.1.52ep 1/2
>>> HomeKit: [Client 2] Pair Verify Step 2/2
>>> HomeKit: [Client 2] Found pairing with 0x0
CLIENT JUST VERIFIED







HTTP FLAG IS 0







Free Heap: 22764
http task started
>>> HomeKit: [Client 2] Verification successful, secure session established
HTTP get task starting...
Free Heap: 18552
Running HTTP get request...
Temporarily killing http task, sensor values are not ready
>>> HomeKit: [Client 3] Pair Verify Step 2/2
>>> HomeKit: [Client 3] Found pairing with 0x0
CLIENT JUST VERIFIED







HTTP FLAG IS 0







Free Heap: 18524
http task started
>>> HomeKit: [Client 3] Verification successful, secure session established
>>> HomeKit: [Client 2] Get Accessories
HTTP get task starting...
Free Heap: 12708
Running HTTP get request...
Temporarily killing http task, sensor values are not ready
>>> HomeKit: [Client 3] Get Accessories
>>> HomeKit: [Client 2] Get Characteristics
>>> HomeKit: [Client 2] Requested characteristic info for 1.6 ("Firmware Revision")
>>> HomeKit: [Client 2] Get Characteristics
>>> HomeKit: [Client 2] Requested characteristic info for 2.6 ("Firmware Revision")
>>> HomeKit: [Client 2] Update Characteristics
>>> HomeKit: [Client 2] Unsubscribed from notifications of characteristic 2.19 ("Motion Detected")
mDNS: Announcing 2 HomekitSensor-C88998
>>> HomeKit: [Client 3] Update Characteristics
>>> HomeKit: [Client 3] Unsubscribed from notifications of characteristic 2.19 ("Motion Detected")
>>> HomeKit: [Client 4] Got new client connection from 192.168.1.51
>>> HomeKit: [Client 3]  Have existing connection from 192.168.1.19
>>> HomeKit: [Client 2]  Have existing connection from 192.168.1.52
>>> HomeKit: [Client 1]  Have existing connection from 192.168.1.42
CLIENT JUST CONNECTED
>>> HomeKit: [Client 4] Pair Verify Step 1/2
>>> HomeKit: [Client 4] Pair Verify Step 2/2
>>> HomeKit: [Client 4] Found pairing with 0x0
CLIENT JUST VERIFIED







HTTP FLAG IS 0







Free Heap: 22412
http task started
>>> HomeKit: [Client 4] Verification successful, secure session established
HTTP get task starting...
Free Heap: 18084
Running HTTP get request...
Temporarily killing http task, sensor values are not ready
>>> HomeKit: [Client 4] Get Accessories
>>> HomeKit: [Client 4] Update Characteristics
>>> HomeKit: [Client 4] Unsubscribed from notifications of characteristic 2.19 ("Motion Detected")
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 4] Requested characteristic info for 2.6 ("Firmware Revision")
>>> HomeKit: [Client 4] Get Characteristics
>>> HomeKit: [Client 4] Requested characteristic info for 1.6 ("Firmware Revision")
mDNS: Announcing 3 HomekitSensor-C88998
mDNS: Announcing 4 HomekitSensor-C88998
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Updating characteristic 1.10 ("Active") with integer 0

UPDATE ACTIVE: Active Status: 0, Current State: 0, Target State: 0
...Sending OFF command...
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Updating characteristic 1.13 ("Target Heater Cooler State") with integer 1
UPDATE STATE: Active State: 0, Current State: 0, Target State: 1
>>> HomeKit: [Client 1] Updating characteristic 1.10 ("Active") with integer 1

UPDATE ACTIVE: Active Status: 1, Current State: 0, Target State: 1
UPDATE TEMP: Active Status: 1, Current State: 0, Target State: 1
Target temp: 22.0
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Updating characteristic 1.13 ("Target Heater Cooler State") with integer 1
UPDATE STATE: Active State: 1, Current State: 2, Target State: 1
>>> HomeKit: [Client 1] Updating characteristic 1.10 ("Active") with integer 1

UPDATE ACTIVE: Active Status: 1, Current State: 2, Target State: 1
UPDATE TEMP: Active Status: 1, Current State: 2, Target State: 1
Target temp: 22.0
>>> HomeKit: [Client 1] Get Characteristics
>>> HomeKit: [Client 1] Requested characteristic info for 1.6 ("Firmware Revision")
>>> HomeKit: [Client 1] Get Characteristics
>>> HomeKit: [Client 1] Requested characteristic info for 2.6 ("Firmware Revision")
>>> HomeKit: [Client 1] Update Characteristics
>>> HomeKit: [Client 1] Updating characteristic 1.10 ("Active") with integer 0

UPDATE ACTIVE: Active Status: 0, Current State: 2, Target State: 1
...Sending OFF command...

**Comment by peros550** [comment] 2021-01-30 23:30
@cab113 @renandw just made a little change. Could you please download my latest commit and try again?

**Comment by cab113** [comment] 2021-01-31 05:37
@peros550 @renandw , yes this one does pair but losses homekit connection after reboot log attached 

>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: xxxxxxxxxxxx
>>> HomeKit: Found admin pairing with 9C328333-4D0A-42B6-8F4D-FA7A2A731F66, disabling pair setup
>>> HomeKit: Configuring mDNS
HomeKit: adding mDNS TXT record md=model_unknown
HomeKit: adding mDNS TXT record pv=1.0
HomeKit: adding mDNS TXT record id=xxxxxxxxxxxx
HomeKit: adding mDNS TXT record c#=1
HomeKit: adding mDNS TXT record s#=1
HomeKit: adding mDNS TXT record ff=0
HomeKit: adding mDNS TXT record sf=0
HomeKit: adding mDNS TXT record ci=9


STARTING HTTP SEVER . . .

SERVER JUST INITIALIZED
Started UDP logging1
Found pairing, starting timers
Initializing AC parameters
mDNS: Delaying probe until IP is acquired
Got IP, resuming mDNS
mDNS: Probing 1 HomekitSensor-49D1F1
mDNS: Failed to send broadcast (code 118)
mDNS: Probing 1 HomekitSensor-49D1F1
mDNS: Failed to send broadcast (code 118)
mDNS: Probing 2 HomekitSensor-49D1F1
mDNS: Failed to send broadcast (code 118)
mDNS: Probing 3 HomekitSensor-49D1F1
mDNS: Failed to send broadcast (code 118)
mDNS: Probe successful, announcing HomekitSensor-49D1F1 TXT md=model_unknown pv=1.0 id=xxxxxxxxxxxx c#=1 s#=1 ff=0 sf=0 ci=9
mDNS: Failed to send broadcast (code 118)
ip:192.168.1.49,mask:255.255.255.0,gw:192.168.1.1
mDNS: Announcing 1 HomekitSensor-49D1F1
mDNS: Announcing 2 HomekitSensor-49D1F1
mDNS: Announcing 3 HomekitSensor-49D1F1

**Comment by peros550** [comment] 2021-01-31 10:28
@cab113 I can't reproduce the issue currently in my network. While the device is not available: 

a)  does it respond to pings? 
b) are you able to load the new webserver (in your case http://192.168.1.49:81 )

**Comment by cab113** [comment] 2021-02-01 01:20
@peros550 this code pairs fine but after power cycle it stops homekit server from loading, i can ping the device and confirm its online and web server is reachable on port 81. homekit server doesnt respond on reboot....

**Comment by renandw** [comment] 2021-02-01 22:02
Hello guys. I am spending a lot of time in a travel due to my job. I hope to test it on Saturday. Thanks a lot for spending some time with it peros.

**Comment by peros550** [comment] 2021-02-01 23:16
@renandw no worries, send your feedback at your earliest convenience. 

@cab113 one more update. Because I cannot reproduce the issue at my home, I am testing various ideas to try to isolate the problem, and see if it fixes the problem. Please let me have your feedback as soon as you test it.

**Comment by renandw** [comment] 2021-02-10 12:05
@peros550 
Again, thanks for looking to this issue.
I've tried yesterday to compile your code and it worked really good. No problems at all.
Thanks a lot!!

@cab113 hope that it works for you too!!

**Comment by peros550** [comment] 2021-02-10 13:45
@renandw you are welcome! I hope will fix it for good. 

so my latest commit simply removed the part of the code (@cab113 found) which set the esp8266 hostname to something human readable in the router's menu. Very strange because this part of the code was introduced back in Jan 22, 2020. I'm wondering if something introduced later, with my updates after Aug '20, comes in contrast to setting the hostname. 

I'll try to think of a solution about this. 

Could I please ask for some information from your side? Because I still can't reproduce the issue on my network, but only at another home which has a router from TP-Link. Would it be possible to let me know what type of router do you have ?

**Comment by cab113** [comment] 2021-02-11 00:28
@peros550 @renandw , the new code pairs and works perfectly. thank you. On other note since you mentioned TP-link router - my main router is TP-link and confirming pairing problems does happen when esp is paired on TP-link wifi and Netcomm Router, i dont have any other to test this on. Maybe the name structure system is not supported by some manufactures or hardware. 

Again thank you.

**Comment by cab113** [comment] 2021-02-15 03:18
@peros550 , is it possible to add ir receive to this repo to update the server if status is changed by a remote, say i turned it on to cool @ 18c but someone at home has turned it to 20c using the remote - feature could update the server and display the change in homekit. an example of this is in [https://github.com/Mixiaoxiao/ESP8266-IR-HOMEKIT](url) . only thing is Wang's doesn't support temperature sensors and other sensors like yours does.

**Comment by peros550** [comment] 2021-02-15 08:10
@cab113 it's a good idea I have also thought about this problem in the past. 

The firmware you pointed is based on the Arduino framework and has access to https://github.com/crankyoldgit/IRremoteESP8266 library. On the other hand, this firmware is based on esp-open-rtos, because Maxim's esp-homekit library is based on esp-open-rtos and unfortunately the IRremoteESP8266 library is not compatible with esp-open-rtos based code. 

I wanted to partially solve the problem using a different approach. For example, after issuing a command to the A/C (i.e. heat to 25C) if the room's current temperature isn't increasing for 1-2hours, then the A/C state would return to OFF. 
This is only a partial solution and I'm still trying to find of any othe way I could possible solve this problem.

**Comment by peros550** [comment] 2021-02-22 13:03
I'm going to close this issue. If by any chance the issue remains, please step in and comment below.

**Closed as completed by peros550** 2021-02-22 13:03 UTC
